@extends('layouts.app')

@section('content')
<?php
$UserLogindetails = auth()->user();
$procurement_add               =   DB::table('access')->where('module_name','procurement')->where('role', $UserLogindetails->type)->where('add','1')->count();
$procurement_edit              =   DB::table('access')->where('module_name','procurement')->where('role', $UserLogindetails->type)->where('edit','1')->count();
$procurement_delete            =   DB::table('access')->where('module_name','procurement')->where('role', $UserLogindetails->type)->where('delete','1')->count();
?>
<div class="space-y-6">

    <!-- HEADER -->
    <div class="flex items-center justify-between">

        <div>
            <h1 class="text-2xl font-bold text-slate-900">
                Automated Procurement & Ordering
            </h1>

            <p class="text-sm text-slate-500 mt-1">
                AI-powered purchasing, supplier automation & procurement workflows
            </p>
        </div>
    <?php if($procurement_add != 0){?>
        <a href="{{ route('procurements.addData') }}"
           class="px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white shadow-lg">
            + Create Purchase Order
        </a>
    <?php } ?>
    </div>
@include('components.flash_message')
    <!-- KPI CARDS -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-5">

        <div class="bg-white rounded-2xl shadow border p-5">
            <p class="text-sm text-slate-500">Open Purchase Orders</p>
            <h2 class="text-3xl font-bold mt-2 text-slate-900">42</h2>
        </div>

        <div class="bg-white rounded-2xl shadow border p-5">
            <p class="text-sm text-slate-500">Pending Approvals</p>
            <h2 class="text-3xl font-bold mt-2 text-orange-500">8</h2>
        </div>

        <div class="bg-white rounded-2xl shadow border p-5">
            <p class="text-sm text-slate-500">Auto Orders Generated</p>
            <h2 class="text-3xl font-bold mt-2 text-cyan-600">21</h2>
        </div>

        <div class="bg-white rounded-2xl shadow border p-5">
            <p class="text-sm text-slate-500">Supplier Integrations</p>
            <h2 class="text-3xl font-bold mt-2 text-green-600">14</h2>
        </div>

    </div>

    <!-- MAIN GRID -->
    <div class="grid grid-cols-1 xl:grid-cols-3 gap-6">

        <!-- AI RECOMMENDATIONS -->
        <div class="xl:col-span-2 bg-white rounded-2xl shadow border p-6">

            <div class="flex items-center justify-between mb-5">

                <div>
                    <h3 class="font-semibold text-slate-900">
                        🤖 AI Procurement Recommendations
                    </h3>

                    <p class="text-sm text-slate-500">
                        Smart reorder suggestions generated by AI engine
                    </p>
                </div>

                <button class="px-4 py-2 rounded-lg bg-slate-900 text-white text-sm">
                    Generate Orders
                </button>

            </div>

            <div class="overflow-x-auto">

        <table id="manage_procurements" class="display w-full text-sm">

            <thead class="bg-slate-50 text-slate-600">
                <tr>
                    <th class="text-left p-4">Po Number</th>
                    <th class="text-left p-4">Expected Delivery Date</th>
                    <th class="text-center p-4">Action</th>
                </tr>
            </thead>

            <tbody class="divide-y">

                <?php foreach($procurements as $procurement) {                   
                ?>

                <tr class="hover:bg-slate-50 transition">

                    <td class="p-4">
                        {{ $procurement->po_number }}
                    </td>
                    <td class="p-4">
                        {{ print_date($procurement->expected_delivery_date) }}
                    </td>

                    <td class="p-4">
                        <a href="<?php echo route('procurements.singleData', ['id' => $procurement->id]); ?>" class="px-3 py-1 rounded-lg bg-blue-100 text-blue-600 mr-2">View</a>
                        <a href="{{ route('procurements.editData', $procurement->id) }}"
                            class="px-3 py-1 rounded-lg bg-blue-100 text-blue-600 mr-2 hover:bg-blue-200 transition">
                                Edit
                            </a>
                        
                        <a href="{{ route('procurements.viewData', ['delete_procurement' => base64_encode($procurement->id)]) }}"
                           onclick="return confirm('Are you sure you want to delete this procurement <?php echo $procurement->po_number; ?>?')"
                           class="px-3 py-1 rounded-lg bg-red-100 text-red-600">
                            Delete
                        </a>
                        

                    </td>

                </tr>

                <?php } ?>

            </tbody>

        </table>

    </div>


        </div>

        <!-- SUPPLIER PANEL -->
        <div class="bg-white rounded-2xl shadow border p-6">

            <h3 class="font-semibold text-slate-900 mb-5">
                🚚 Supplier Activity
            </h3>

            <div class="space-y-4">

                <div class="p-4 rounded-xl border bg-slate-50">
                    <div class="flex items-center justify-between">
                        <h4 class="font-medium">FreshFarm Foods</h4>
                        <span class="text-xs px-2 py-1 rounded-full bg-green-100 text-green-600">
                            Active
                        </span>
                    </div>

                    <p class="text-sm text-slate-500 mt-1">
                        Last delivery completed successfully
                    </p>
                </div>

                <div class="p-4 rounded-xl border bg-slate-50">
                    <div class="flex items-center justify-between">
                        <h4 class="font-medium">DairyPro Ltd</h4>
                        <span class="text-xs px-2 py-1 rounded-full bg-yellow-100 text-yellow-700">
                            Delayed
                        </span>
                    </div>

                    <p class="text-sm text-slate-500 mt-1">
                        Delivery expected in 4 hours
                    </p>
                </div>

                <div class="p-4 rounded-xl border bg-slate-50">
                    <div class="flex items-center justify-between">
                        <h4 class="font-medium">GrainHub</h4>
                        <span class="text-xs px-2 py-1 rounded-full bg-blue-100 text-blue-600">
                            Synced
                        </span>
                    </div>

                    <p class="text-sm text-slate-500 mt-1">
                        Catalog & pricing updated automatically
                    </p>
                </div>

            </div>

        </div>

    </div>

    <!-- PURCHASE ORDER TABLE -->
    

</div>



<!-- DataTable Script -->
<script>
$(document).ready(function () {

    $('#manage_procurements').DataTable({

        responsive: true,

        pageLength: 10,

        lengthMenu: [
            [10, 25, 50, 100, -1],
            [10, 25, 50, 100, "All"]
        ],

        columnDefs: [
            {
                orderable: false,
                targets: [5]
            }
        ]

    });

});
</script>
@endsection