@extends('layouts.app')

@section('content')
<?php
$UserLogindetails = auth()->user();
$procurement_add               =   DB::table('access')->where('module_name','procurement')->where('role', $UserLogindetails->type)->where('add','1')->count();
$procurement_edit              =   DB::table('access')->where('module_name','procurement')->where('role', $UserLogindetails->type)->where('edit','1')->count();
$procurement_delete            =   DB::table('access')->where('module_name','procurement')->where('role', $UserLogindetails->type)->where('delete','1')->count();
?>
<div class="space-y-6">

    <!-- HEADER -->
    <div class="flex items-center justify-between">

        <div>
            <h1 class="text-2xl font-bold text-slate-900">
                Automated Procurement & Ordering
            </h1>

            <p class="text-sm text-slate-500 mt-1">
                AI-powered purchasing, supplier automation & procurement workflows
            </p>
        </div>
    <?php if($procurement_add != 0){?>
        <a href="{{ route('procurements.addData') }}"
           class="px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white shadow-lg">
            + Create Purchase Order
        </a>
    <?php } ?>
    </div>

    <!-- KPI CARDS -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-5">

        <div class="bg-white rounded-2xl shadow border p-5">
            <p class="text-sm text-slate-500">Open Purchase Orders</p>
            <h2 class="text-3xl font-bold mt-2 text-slate-900">42</h2>
        </div>

        <div class="bg-white rounded-2xl shadow border p-5">
            <p class="text-sm text-slate-500">Pending Approvals</p>
            <h2 class="text-3xl font-bold mt-2 text-orange-500">8</h2>
        </div>

        <div class="bg-white rounded-2xl shadow border p-5">
            <p class="text-sm text-slate-500">Auto Orders Generated</p>
            <h2 class="text-3xl font-bold mt-2 text-cyan-600">21</h2>
        </div>

        <div class="bg-white rounded-2xl shadow border p-5">
            <p class="text-sm text-slate-500">Supplier Integrations</p>
            <h2 class="text-3xl font-bold mt-2 text-green-600">14</h2>
        </div>

    </div>

    <!-- MAIN GRID -->
    <div class="grid grid-cols-1 xl:grid-cols-3 gap-6">

        <!-- AI RECOMMENDATIONS -->
        <div class="xl:col-span-2 bg-white rounded-2xl shadow border p-6">

            <div class="flex items-center justify-between mb-5">

                <div>
                    <h3 class="font-semibold text-slate-900">
                        🤖 AI Procurement Recommendations
                    </h3>

                    <p class="text-sm text-slate-500">
                        Smart reorder suggestions generated by AI engine
                    </p>
                </div>

                <button class="px-4 py-2 rounded-lg bg-slate-900 text-white text-sm">
                    Generate Orders
                </button>

            </div>

            <div class="overflow-x-auto">

                <table class="w-full text-sm">

                    <thead class="bg-slate-50 text-slate-600">
                        <tr>
                            <th class="text-left p-3">Item</th>
                            <th class="text-left p-3">Current Stock</th>
                            <th class="text-left p-3">Recommended Qty</th>
                            <th class="text-left p-3">Preferred Vendor</th>
                            <th class="text-left p-3">Priority</th>
                        </tr>
                    </thead>

                    <tbody class="divide-y">

                        <tr class="hover:bg-slate-50 transition">
                            <td class="p-3 font-medium">Chicken Breast</td>
                            <td class="p-3">8 KG</td>
                            <td class="p-3 text-blue-600 font-semibold">+40 KG</td>
                            <td class="p-3">FreshFarm Foods</td>
                            <td class="p-3">
                                <span class="px-3 py-1 rounded-full bg-red-100 text-red-600 text-xs font-medium">
                                    High
                                </span>
                            </td>
                        </tr>

                        <tr class="hover:bg-slate-50 transition">
                            <td class="p-3 font-medium">Milk</td>
                            <td class="p-3">12 L</td>
                            <td class="p-3 text-blue-600 font-semibold">+25 L</td>
                            <td class="p-3">DairyPro Ltd</td>
                            <td class="p-3">
                                <span class="px-3 py-1 rounded-full bg-yellow-100 text-yellow-700 text-xs font-medium">
                                    Medium
                                </span>
                            </td>
                        </tr>

                        <tr class="hover:bg-slate-50 transition">
                            <td class="p-3 font-medium">Rice</td>
                            <td class="p-3">120 KG</td>
                            <td class="p-3 text-blue-600 font-semibold">+200 KG</td>
                            <td class="p-3">GrainHub</td>
                            <td class="p-3">
                                <span class="px-3 py-1 rounded-full bg-green-100 text-green-700 text-xs font-medium">
                                    Normal
                                </span>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>

        </div>

        <!-- SUPPLIER PANEL -->
        <div class="bg-white rounded-2xl shadow border p-6">

            <h3 class="font-semibold text-slate-900 mb-5">
                🚚 Supplier Activity
            </h3>

            <div class="space-y-4">

                <div class="p-4 rounded-xl border bg-slate-50">
                    <div class="flex items-center justify-between">
                        <h4 class="font-medium">FreshFarm Foods</h4>
                        <span class="text-xs px-2 py-1 rounded-full bg-green-100 text-green-600">
                            Active
                        </span>
                    </div>

                    <p class="text-sm text-slate-500 mt-1">
                        Last delivery completed successfully
                    </p>
                </div>

                <div class="p-4 rounded-xl border bg-slate-50">
                    <div class="flex items-center justify-between">
                        <h4 class="font-medium">DairyPro Ltd</h4>
                        <span class="text-xs px-2 py-1 rounded-full bg-yellow-100 text-yellow-700">
                            Delayed
                        </span>
                    </div>

                    <p class="text-sm text-slate-500 mt-1">
                        Delivery expected in 4 hours
                    </p>
                </div>

                <div class="p-4 rounded-xl border bg-slate-50">
                    <div class="flex items-center justify-between">
                        <h4 class="font-medium">GrainHub</h4>
                        <span class="text-xs px-2 py-1 rounded-full bg-blue-100 text-blue-600">
                            Synced
                        </span>
                    </div>

                    <p class="text-sm text-slate-500 mt-1">
                        Catalog & pricing updated automatically
                    </p>
                </div>

            </div>

        </div>

    </div>

    <!-- PURCHASE ORDER TABLE -->
    <div class="bg-white rounded-2xl shadow border overflow-hidden">

        <div class="p-5 border-b flex items-center justify-between">

            <div>
                <h3 class="font-semibold text-slate-900">
                    📄 Purchase Orders
                </h3>

                <p class="text-sm text-slate-500">
                    Track procurement orders & approval workflows
                </p>
            </div>

            <button class="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-sm">
                View All
            </button>

        </div>

        <div class="overflow-x-auto">

            <table class="w-full text-sm">

                <thead class="bg-slate-50 text-slate-600">
                    <tr>
                        <th class="text-left p-4">PO Number</th>
                        <th class="text-left p-4">Vendor</th>
                        <th class="text-left p-4">Amount</th>
                        <th class="text-left p-4">Delivery Date</th>
                        <th class="text-left p-4">Status</th>
                        <th class="text-left p-4">Approval</th>
                    </tr>
                </thead>

                <tbody class="divide-y">

                    <tr class="hover:bg-slate-50 transition">
                        <td class="p-4 font-medium">PO-2041</td>
                        <td class="p-4">FreshFarm Foods</td>
                        <td class="p-4">₹ 18,500</td>
                        <td class="p-4">12 May 2026</td>
                        <td class="p-4">
                            <span class="px-3 py-1 rounded-full bg-blue-100 text-blue-600 text-xs">
                                In Transit
                            </span>
                        </td>
                        <td class="p-4 text-green-600 font-medium">
                            Approved
                        </td>
                    </tr>

                    <tr class="hover:bg-slate-50 transition">
                        <td class="p-4 font-medium">PO-2042</td>
                        <td class="p-4">DairyPro Ltd</td>
                        <td class="p-4">₹ 6,200</td>
                        <td class="p-4">13 May 2026</td>
                        <td class="p-4">
                            <span class="px-3 py-1 rounded-full bg-yellow-100 text-yellow-700 text-xs">
                                Pending
                            </span>
                        </td>
                        <td class="p-4 text-orange-500 font-medium">
                            Waiting
                        </td>
                    </tr>

                </tbody>

            </table>

        </div>

    </div>

</div>

@endsection